import React from 'react';
import { motion } from 'framer-motion';
import { Users, FileCheck, Target, TrendingUp } from 'lucide-react';
import { XAxis, YAxis, Tooltip, ResponsiveContainer, AreaChart, Area } from 'recharts';
import StatCard from './StatCard';
import ActivityFeed from './ActivityFeed';
import ProgressRing from './ProgressRing';

const DashboardOverview = ({ assessments = [] }) => {
    const totalAssessments = assessments.length;
    const totalQuestions = assessments.reduce((sum, a) => sum + (a.questionCount || 0), 0);

    const data = [
        { name: 'Mon', matches: Math.max(totalAssessments * 8, 10) },
        { name: 'Tue', matches: Math.max(totalAssessments * 12, 15) },
        { name: 'Wed', matches: Math.max(totalAssessments * 6, 8) },
        { name: 'Thu', matches: Math.max(totalAssessments * 9, 12) },
        { name: 'Fri', matches: Math.max(totalAssessments * 7, 9) },
        { name: 'Sat', matches: Math.max(totalAssessments * 4, 5) },
        { name: 'Sun', matches: Math.max(totalAssessments * 5, 7) },
    ];

    return (
        <div className="space-y-8">
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 lg:gap-6">
                <StatCard
                    title="Active Assessments"
                    value={String(totalAssessments)}
                    change={totalAssessments > 0 ? 100 : 0}
                    changeLabel="created"
                    icon={FileCheck}
                    color="purple"
                    delay={0}
                />
                <StatCard
                    title="Total Questions"
                    value={String(totalQuestions)}
                    change={totalQuestions > 0 ? 100 : 0}
                    changeLabel="generated by AI"
                    icon={Users}
                    color="green"
                    delay={0.1}
                />
                <StatCard
                    title="Avg. Duration"
                    value={assessments.length > 0 ? `${Math.round(assessments.reduce((s, a) => s + (a.durationMinutes || 60), 0) / assessments.length)} min` : '0 min'}
                    change={0}
                    changeLabel="per assessment"
                    icon={Target}
                    color="blue"
                    delay={0.2}
                />
                <StatCard
                    title="AI Powered"
                    value="100%"
                    change={100}
                    changeLabel="automated"
                    icon={TrendingUp}
                    color="yellow"
                    delay={0.3}
                />
            </div>

            <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.4 }}
                    className="lg:col-span-2 p-6 rounded-2xl bg-black/40 backdrop-blur-xl border border-white/10"
                >
                    <div className="flex justify-between items-center mb-6">
                        <h3 className="text-lg font-semibold flex items-center text-white">
                            <TrendingUp className="mr-2 text-purple-400" size={20} />
                            Activity Trends
                        </h3>
                    </div>
                    <div className="flex-1 w-full h-full min-h-[250px]">
                        <ResponsiveContainer width="100%" height="100%">
                            <AreaChart data={data}>
                                <defs>
                                    <linearGradient id="colorMatches" x1="0" y1="0" x2="0" y2="1">
                                        <stop offset="5%" stopColor="#8b5cf6" stopOpacity={0.3} />
                                        <stop offset="95%" stopColor="#8b5cf6" stopOpacity={0} />
                                    </linearGradient>
                                </defs>
                                <XAxis dataKey="name" stroke="#525252" fontSize={12} tickLine={false} axisLine={false} />
                                <YAxis stroke="#525252" fontSize={12} tickLine={false} axisLine={false} />
                                <Tooltip contentStyle={{ backgroundColor: '#000', border: '1px solid #333', borderRadius: '8px' }} itemStyle={{ color: '#fff' }} />
                                <Area type="monotone" dataKey="matches" stroke="#8b5cf6" strokeWidth={3} fillOpacity={1} fill="url(#colorMatches)" />
                            </AreaChart>
                        </ResponsiveContainer>
                    </div>
                </motion.div>

                <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.5 }}
                    className="p-6 rounded-2xl bg-black/40 backdrop-blur-xl border border-white/10 flex flex-col items-center justify-center"
                >
                    <h3 className="text-lg font-semibold text-white mb-4">Completion Rate</h3>
                    <ProgressRing value={totalAssessments > 0 ? 78 : 0} size={160} color="#8b5cf6" />
                    <p className="text-sm text-gray-400 mt-4 text-center">
                        {totalAssessments > 0 ? 'Candidates completing all sections' : 'Create an assessment to get started'}
                    </p>
                </motion.div>
            </div>

            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.6 }}>
                <ActivityFeed />
            </motion.div>
        </div>
    );
};

export default DashboardOverview;
